### ISSUE TITLE
Incorrect name for : athena__generate_elementary_profile_args in macros/utils/cross_db_utils/generate_elementary_profile_args.sql

### ISSUE THREAD

**Issue by gstoel** [elementary-data/dbt-data-reliability#612]
Testing out the athena update for elementary. 
when running the  `dbt run-operation elementary.generate_elementary_cli_profile` command an error is returned: 
`Adapter "athena" is not supported on Elementary.`

Zooming in on the macro which causes this: `athena__generate_elementary_profile_args`  shows that [the athena macro ](https://github.com/elementary-data/dbt-data-reliability/blob/b234a2f460813d477b87ef464a7350270da0c843/macros/utils/cross_db_utils/generate_elementary_profile_args.sql#L105) is named `athena__generate_elementary_cli_profile `, which I think is incorrect and should be `athena__generate_elementary_profile_args`

**Comment by Maayan-s** [comment]
@haritamar

**Comment by haritamar** [comment]
Updating that this issue was due to the Athena support not being released yet in an official version.
Relevant community thread [here](https://elementary-community.slack.com/archives/C02CTC89LAX/p1697812888632319)

Closing this ticket for now.
