### ISSUE TITLE
dbt_invocations model > job_name column showing up as 'null'

### ISSUE THREAD

**Issue by wusanny** [elementary-data/dbt-data-reliability#683]
**Issue description**
Hello, we have a client who is using elementary dbt package in dbt Cloud and reported that they are not getting a value returned for the `job_name` column in the `dbt_invocations` model. Entire column just have 'null' values. 

We tested and it seemed to be the case for us as well. Are we missing a config somewhere in order to have this value returned? 

**Steps to reproduce the behavior:**
1. Install the package in dbt Cloud's IDE as per [Quick Start instructions here](https://github.com/elementary-data/dbt-data-reliability/tree/0.14.1/?tab=readme-ov-file#quick-start)
2. Run a production job
3. Query in the datawarehouse (in this case Snowflake) for the `dbt_invocations` model
4. See that the `job_name` column has no value

**Screenshots**
<img width="963" alt="dbt_invocations   job_name column" src="https://github.com/elementary-data/dbt-data-reliability/assets/141895372/6aa65bc9-8e42-4e3b-a743-41d1e2c040cb">

**Other documents**
I have also attached the csv file download of the model here - [dbt_invocations (test).csv](https://github.com/elementary-data/dbt-data-reliability/files/14676218/dbt_invocations.test.csv), for reference. 

**Additional comments**
On elementary [docs here](https://docs.elementary-data.com/dbt/package-models#dbt-invocations), it seems to suggest that these data should automatically populate if we are using an orchestrator that Elementary natively supports (which we are with dbt Cloud). 

**Version**
dbt package version: 0.14.1

Thank you!

**Comment by haritamar** [comment]
Hi @wusanny ,
Sorry for only just responding. 
By default, dbt Cloud only provides the job ID parameter automatically. If you'd like to also have a JOB_NAME within `dbt_invocations`, you need to configure it in dbt Cloud in one of the two ways:

- As the environment variable `DBT_JOB_NAME`
- As the dbt var `job_name`

Thanks,
Itamar

(Also for future reference - we prefer to manage issues in the [main Elementary repo](https://github.com/elementary-data/elementary), so please open future issues there)
