### ISSUE TITLE
Temporary tables for volume and freshness tests are not properly cleaned on Athena

### ISSUE THREAD

**Issue by bebbo203** [elementary-data/dbt-data-reliability#710]
**Describe the bug**
After a succesful run of volume and source freshness tests, tables in the form:

`data_monitoring_metrics_tmp_<timestamp>`

are left in Athena and s3.
Moreover, while not present in Athena, is still possible to find files about other temporary tables in the form:

`test_<hex_code>_elementary_volume_anomalies_<model_name>_<other_descs>`

in the s3 bucket

**To Reproduce**

1. Add an Elementary's volume or freshness test to any model or source in your dbt project while using dbt-athena adapter
2. Run `dbt run --select elementary`
3. Run `dbt test`
4. Check the tables in athena and in the bucket `s3_data_dir`

**Expected behavior**
Temporary tables must be completely dropped after a run (metadata + parquet files in S3).

**Environment (please complete the following information):**

- edr Version: 0.14.1
- dbt package Version: 0.14.0
- dbt version: 1.7.13

**Comment by haritamar** [comment]
Closing this issue to keep discussion in the main Elementary repo

elementary-data/elementary#1514
