### ISSUE TITLE
Upgrading to 0.16.0 breaks column_anomalies tests due to missing metric_type

### ISSUE THREAD

**Issue by PatFitzner** [elementary-data/dbt-data-reliability#746]
We are running Elementary Cloud with dbt cloud versionless.
Yesterday we upgraded our dbt-data-reliability version from 0.15.2 to 0.16.0, and today we have found that all our **column_anomalies** tests have thrown an error with the message `Unrecognized name: metric_type; Did you mean metric_name?`

We suspect this is related to [this change](https://github.com/elementary-data/dbt-data-reliability/commit/f9a2f8f778fa9923e1447e50e44bc6a3f522d2b1).

Since we have seen no breaking changes being disclaimed on the release notes, nor instructions on how to adapt to the introbuction of  `metric_type`, we have resolved to roll back to 0.15.2.

**Comment by ellakz** [comment]
Hi @PatFitzner ,
Can you please copy your test settings here?

**Comment by ofek1weiss** [comment]
Hey @PatFitzner , did you run `dbt run -s elementary` after the upgrade?

**Comment by PatFitzner** [comment]
> Hey @PatFitzner , did you run `dbt run -s elementary` after the upgrade?

Hello! No, we did not. Is that something we should be doing after every version upgrade? Because I've checked in both release notes, and in the **Elementary: Upgrade dbt package.** PR that the elementary-data bot added automatically in our project, and could not find any references to this.


> Hi @PatFitzner , Can you please copy your test settings here?

Hey, please excuse my ignorance but I am not sure of what exactly you are requesting. Could you help me understand?

**Comment by ofek1weiss** [comment]
Hey @PatFitzner, the "rule" is to run `dbt run -s elementary` on every minor version upgrade (so no need to run when upgrading from `0.15.1` to `0.15.2` but do need to run when upgrading to `0.16.0`).

We should probably communicate it better in our release notes/cloud pull requests

**Comment by PatFitzner** [comment]
Hi @ofek1weiss !
Thank you for your comment.
I was checking the link you included, but it is related to Elementary OSS, and we are using Elementary Cloud. The only place where we would be able to run `dbt run --select elementary` would be in the dbt cloud IDE, which would have no effect in our production environment, if I am not mistaken.

Could you please confirm that this step is still required for Cloud, and how we should go about it?

Thank you.

**Comment by haritamar** [comment]
HI @PatFitzner !
Just to clarify - do your production jobs also run via dbt cloud, or in another manner?
If they run via dbt Cloud, you can create an additional job for running the Elementary models and execute it.

**Comment by PatFitzner** [comment]
Hey @haritamar !
Indeed, that is the case. I will try that.
Thank you!

**Comment by Maayan-s** [comment]
I am closing the issue for now.

@PatFitzner I also sent you an invite to our mutual Slack channel with your company. 
We have an on-call engineer who provides support in these Slack channels.
